services:
  - type: web
    name: rayen-coif
    runtime: node

    # IMPORTANT :
    # Persistent Disk incompatible avec Free.
    # Utiliser un plan payant.
    plan: starter

    branch: main

    buildCommand: >-
      cd client &&
      npm install &&
      npm run build &&
      cd ../server &&
      npm install &&
      npm run build

    startCommand: cd server && npm start

    healthCheckPath: /api/health

    envVars:
      - key: PORT
        value: 10000

      - key: ADMIN_PASSWORD
        sync: false

      - key: JWT_SECRET
        sync: false

      # SQLite sera stockée sur le Persistent Disk.
      - key: DB_PATH
        value: /var/data/salon.db

    disk:
      name: rayen-coif-data
      mountPath: /var/data
      sizeGB: 1