services:
  - type: web
    name: rayen-coif
    runtime: node
    plan: free
    branch: main

    buildCommand: >
      cd client &&
      npm install &&
      npm run build &&
      cd ../server &&
      npm install &&
      npm run build

    startCommand: cd server && npm start

    healthCheckPath: /api/health

    envVars:
      - key: PORT
        value: 10000

      - key: ADMIN_PASSWORD
        sync: false

      - key: JWT_SECRET
        sync: false

      - key: TURSO_DATABASE_URL
        sync: false

      - key: TURSO_AUTH_TOKEN
        sync: false